import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Bot, GitBranch, GitPullRequest, Play, CheckCircle2, XCircle, FileCode2, Terminal, GitCommit, Upload, Sparkles, Moon, Sun, Save, Trash2, MessageCircle, Send, Square} from 'lucide-react';
import './styles.css';
import {formatTime} from './timer.js';
import {getInitialTheme, nextTheme} from './theme.js';

const API = import.meta.env.VITE_API_URL || '';
const initial = {project_path:'', guide_paths:'', task_id:'podw-205', request:'', base_branch:'main', test_command:'', test_setup_enabled:false, mcp_server_name:'', mcp_failure_mode:'warning', git_provider:'gitlab'};
const defaultBaseBranch=path=>/(^|[\\/])dws[\\/]?$/i.test(path.trim())?'sandbox':'main';
const apiError=(detail,fallback)=>{
  if(typeof detail==='string'&&detail.trim())return detail;
  if(Array.isArray(detail))return detail.map(item=>{const field=Array.isArray(item?.loc)?item.loc.slice(1).join(' / '):'ورودی';return `${field}: ${item?.msg||'مقدار نامعتبر است'}`}).join(' | ')||fallback;
  if(typeof detail?.message==='string')return detail.message;
  return fallback;
};

function Clock(){
  const [now,setNow]=useState(()=>new Date());
  useEffect(()=>{const timer=setInterval(()=>setNow(new Date()),10);return()=>clearInterval(timer)},[]);
  return <time className="clock" dateTime={now.toISOString()} aria-label="زمان فعلی"><small>زمان فعلی</small><b dir="ltr">{formatTime(now)}</b></time>;
}

function DirectionalOutput({text}){
  return String(text??'').split('\n').map((line,index)=><span className="output-line" dir="auto" key={index}>{line||'\u200b'}</span>);
}

function App(){
  const [form,setForm]=useState(initial), [task,setTask]=useState(null), [busy,setBusy]=useState(false), [tab,setTab]=useState('changes'), [notice,setNotice]=useState(''), [chatMessage,setChatMessage]=useState('');
  const [profiles,setProfiles]=useState([]), [selectedProfile,setSelectedProfile]=useState(''), [sessions,setSessions]=useState([]);
  const [startupDefaults,setStartupDefaults]=useState(initial);
  const [theme,setTheme]=useState(()=>getInitialTheme(localStorage,window.matchMedia('(prefers-color-scheme: dark)').matches));
  const outputRef=useRef(null);
  const update=e=>{const {name,value,type,checked}=e.target;const next=type==='checkbox'?checked:value;if(name!=='project_path'||!startupDefaults.project_path||value===startupDefaults.project_path){setForm({...form,[name]:next});return}setForm(current=>({...current,project_path:value,guide_paths:current.guide_paths===startupDefaults.guide_paths?'':current.guide_paths,base_branch:current.base_branch===startupDefaults.base_branch?defaultBaseBranch(value):current.base_branch,test_command:current.test_command===startupDefaults.test_command?'':current.test_command,mcp_server_name:current.mcp_server_name===startupDefaults.mcp_server_name?'':current.mcp_server_name,mcp_failure_mode:current.mcp_failure_mode===startupDefaults.mcp_failure_mode?'warning':current.mcp_failure_mode}))};
  function rememberTask(next){setTask(next);setSessions(current=>[next,...current.filter(item=>item.id!==next.id)]);localStorage.setItem('taskloom-active-session',next.id)}
  useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('taskloom-theme',theme)},[theme]);
  useEffect(()=>{fetch(`${API}/api/defaults`).then(async r=>{if(!r.ok)throw Error('خواندن پیش‌فرض‌ها ناموفق بود');const defaults=await r.json();const loaded={...initial,project_path:defaults.project_path||'',guide_paths:(defaults.guide_paths||[]).join('\n'),base_branch:defaults.base_branch||'main',test_command:defaults.test_command||'',test_setup_enabled:!!defaults.test_setup_enabled,mcp_server_name:defaults.mcp_server_name||'',mcp_failure_mode:defaults.mcp_failure_mode||'warning'};setStartupDefaults(loaded);setForm(current=>current.project_path?current:{...current,...loaded})}).catch(e=>setNotice(e.message))},[]);
  useEffect(()=>{fetch(`${API}/api/profiles`).then(async r=>{if(!r.ok)throw Error('خواندن پروفایل‌ها ناموفق بود');setProfiles(await r.json())}).catch(e=>setNotice(e.message))},[]);
  useEffect(()=>{fetch(`${API}/api/tasks`).then(async r=>{if(!r.ok)throw Error('خواندن سشن‌ها ناموفق بود');const items=await r.json();setSessions(items);const active=items.find(item=>item.id===localStorage.getItem('taskloom-active-session'))||items[0];if(active)setTask(active)}).catch(e=>setNotice(e.message))},[]);
  useEffect(()=>{if(!task||['passed','failed','blocked','stopped'].includes(task.status)||typeof EventSource==='undefined')return;const events=new EventSource(`${API}/api/tasks/${task.id}/events`);events.onmessage=e=>{const next=JSON.parse(e.data);rememberTask(next);if(['passed','failed','blocked','stopped'].includes(next.status))events.close()};events.onerror=()=>events.close();return()=>events.close()},[task?.id,task?.status]);
  useEffect(()=>{ if(!task || ['passed','failed','blocked','stopped'].includes(task.status)) return; const timer=setInterval(async()=>{const r=await fetch(`${API}/api/tasks/${task.id}`); if(r.ok)rememberTask(await r.json())},1400); return()=>clearInterval(timer)},[task?.id,task?.status]);
  useEffect(()=>{const panel=outputRef.current;if(panel&&task&&['queued','running'].includes(task.status))panel.scrollTop=panel.scrollHeight},[task?.live_output,task?.live_response]);
  async function start(e){e.preventDefault();setBusy(true);setNotice('');try{const body={...form,guide_paths:form.guide_paths.split('\n').map(x=>x.trim()).filter(Boolean),test_command:form.test_command||null,mcp_server_name:form.mcp_server_name.trim()||null};const r=await fetch(`${API}/api/tasks`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(apiError(d.detail,'شروع تسک ناموفق بود'));rememberTask(d)}catch(err){setNotice(err.message)}finally{setBusy(false)}}
  async function action(kind,body){setBusy(true);setNotice('');try{const r=await fetch(`${API}/api/tasks/${task.id}/${kind}`,{method:'POST',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(apiError(d.detail,'انجام عملیات ناموفق بود'));rememberTask(d.task);setNotice({commit:'تغییرات با موفقیت commit شدند.',push:'برنچ با موفقیت push شد.','merge-request':'درخواست ادغام با موفقیت ساخته شد.'}[kind])}catch(e){setNotice(e.message)}finally{setBusy(false)}}
  async function runTestSetup(){if(!task)return;if(!window.confirm('دیتابیس تست محلی و قابل حذف است؟ این عملیات داده‌های آن را reset می‌کند.'))return;setBusy(true);setNotice('');try{const r=await fetch(`${API}/api/test-setup`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project_path:task.project_path,confirm_test_database:true})});const d=await r.json();if(!r.ok)throw Error(apiError(d.detail,'اجرای setup تست ناموفق بود'));setTask(current=>({...current,test_setup_output:d.output}));setTab('test-setup');setNotice('Setup محیط تست با موفقیت انجام شد.')}catch(e){setNotice(e.message)}finally{setBusy(false)}}
  async function generateCommitMessage(){if(!task?.codex_thread_id)return;setBusy(true);setNotice('');try{const r=await fetch(`${API}/api/tasks/${task.id}/commit-message`,{method:'POST'});const d=await r.json();if(!r.ok)throw Error(apiError(d.detail,'ساخت پیام commit ناموفق بود'));setTask(current=>({...current,commit_message:d.message}));setNotice('پیام commit پیشنهادی Codex در فیلد قرار گرفت.')}catch(e){setNotice(e.message)}finally{setBusy(false)}}
  async function sendMessage(e){e.preventDefault();const message=chatMessage.trim();if(!message||!task?.codex_thread_id)return;setBusy(true);setNotice('');try{const r=await fetch(`${API}/api/tasks/${task.id}/messages`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message})});const d=await r.json();if(!r.ok)throw Error(apiError(d.detail,'ارسال پیام ناموفق بود'));rememberTask(d);setChatMessage('');setTab('summary')}catch(err){setNotice(err.message)}finally{setBusy(false)}}
  async function stopTask(){if(!task)return;setBusy(true);setNotice('');try{const r=await fetch(`${API}/api/tasks/${task.id}/stop`,{method:'POST'});const d=await r.json();if(!r.ok)throw Error(apiError(d.detail,'توقف Codex ناموفق بود'));rememberTask(d);setTab('summary');setNotice(d.codex_thread_id?'Codex متوقف شد؛ اصلاحیه را در کادر گفتگو بفرست.':'اجرا پیش از ساخته‌شدن سشن متوقف شد؛ برای ادامه یک تسک جدید شروع کن.')}catch(err){setNotice(err.message)}finally{setBusy(false)}}
  function submitChatOnEnter(e){if(e.key!=='Enter'||e.shiftKey||e.nativeEvent.isComposing)return;e.preventDefault();e.currentTarget.form?.requestSubmit()}
  async function chooseSession(id){if(!id){setTask(null);localStorage.removeItem('taskloom-active-session');return}setBusy(true);setNotice('');try{const r=await fetch(`${API}/api/tasks/${id}`);const d=await r.json();if(!r.ok)throw Error(apiError(d.detail,'خواندن سشن ناموفق بود'));rememberTask(d)}catch(err){setNotice(err.message)}finally{setBusy(false)}}
  function chooseProfile(name){setSelectedProfile(name);const profile=profiles.find(item=>item.name===name);if(profile)setForm(current=>({...current,project_path:profile.project_path,guide_paths:profile.guide_paths.join('\n'),base_branch:profile.base_branch||defaultBaseBranch(profile.project_path),test_command:profile.test_command||'',test_setup_enabled:!!profile.test_setup_enabled,mcp_server_name:profile.mcp_server_name||'',mcp_failure_mode:profile.mcp_failure_mode||'warning',git_provider:profile.git_provider||'auto'}))}
  async function saveProfile(){const name=(selectedProfile||window.prompt('نام پروفایل پروژه را وارد کنید:')||'').trim();if(!name)return;setBusy(true);setNotice('');try{const profile={name,project_path:form.project_path,guide_paths:form.guide_paths.split('\n').map(x=>x.trim()).filter(Boolean),base_branch:form.base_branch.trim(),test_command:form.test_command||null,test_setup_enabled:form.test_setup_enabled,mcp_server_name:form.mcp_server_name.trim()||null,mcp_failure_mode:form.mcp_failure_mode};const r=await fetch(`${API}/api/profiles/${encodeURIComponent(name)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(profile)});const d=await r.json();if(!r.ok)throw Error(apiError(d.detail,'ذخیره پروفایل ناموفق بود'));setProfiles(current=>[...current.filter(item=>item.name!==name),d].sort((a,b)=>a.name.localeCompare(b.name)));setSelectedProfile(name);setNotice('پروفایل پروژه ذخیره شد.')}catch(e){setNotice(e.message)}finally{setBusy(false)}}
  async function removeProfile(){if(!selectedProfile)return;setBusy(true);setNotice('');try{const r=await fetch(`${API}/api/profiles/${encodeURIComponent(selectedProfile)}`,{method:'DELETE'});if(!r.ok){const d=await r.json();throw Error(apiError(d.detail,'حذف پروفایل ناموفق بود'))}setProfiles(current=>current.filter(item=>item.name!==selectedProfile));setSelectedProfile('');setNotice('پروفایل حذف شد.')}catch(e){setNotice(e.message)}finally{setBusy(false)}}
  const running=task&&!['passed','failed','blocked','stopped'].includes(task.status), passed=task?.status==='passed', codexTyping=task&&['queued','running'].includes(task.status), interruptedReply=task?.status==='stopped'&&task.live_response;
  const changeOutput=codexTyping&&task.live_output?task.live_output:(task?.diff||'در انتظار تغییرات…');
  const outputText=tab==='changes'?changeOutput:tab==='tests'?(task.test_output||'تست‌ها هنوز اجرا نشده‌اند…'):tab==='test-setup'?(task.test_setup_output||'هنوز setup تست اجرا نشده است.'):(task.live_response||task.summary||task.logs.join('\n')||'در حال تحلیل…');
  const gitProviderControl=<label className="git-provider">Git hosting<select name="git_provider" value={form.git_provider} onChange={update}><option value="gitlab">GitLab</option><option value="github">GitHub</option><option value="auto">Auto</option></select></label>;
  return <div className="app" dir="rtl">
    <header><div className="brand"><span className="logo"><Sparkles size={20}/></span><div><b>Taskloom</b><small>Codex delivery console</small></div></div><div className="header-status"><Clock/><button className="theme-toggle" type="button" onClick={()=>setTheme(nextTheme(theme))} aria-label={theme==='dark'?'فعال‌کردن تم روشن':'فعال‌کردن تم تاریک'} aria-pressed={theme==='dark'}>{theme==='dark'?<Sun size={16}/>:<Moon size={16}/>}<span>{theme==='dark'?'روشن':'دارک'}</span></button><div className="online"><i/> Codex محلی</div></div></header>
    <main>
      {/*<section className="intro"><div><span className="eyebrow"><Bot size={15}/></span><p></p></div><div className="orb"><Bot size={46}/></div></section>*/}
      <div className="grid">
        <form className="card form" onSubmit={start}>{gitProviderControl}
          <div className="card-title"><span>تعریف تسک</span><em>01</em></div>
          <div className="profile-picker"><select aria-label="پروفایل پروژه" value={selectedProfile} onChange={e=>chooseProfile(e.target.value)}><option value="">پروفایل پروژه…</option>{profiles.map(profile=><option key={profile.name} value={profile.name}>{profile.name}</option>)}</select><button type="button" onClick={saveProfile} disabled={busy||!form.project_path} title="ذخیره پروفایل"><Save size={16}/><span>{selectedProfile?'به‌روزرسانی':'ذخیره'}</span></button><button className="danger" type="button" onClick={removeProfile} disabled={busy||!selectedProfile} title="حذف پروفایل" aria-label="حذف پروفایل"><Trash2 size={16}/><span>حذف</span></button></div>
          <label>آدرس پروژه <small>با تغییر مسیر، راهنما، تست، MCP و برنچ مبنای پیش‌فرض همان پروژه تنظیم می‌شوند</small><input name="project_path" value={form.project_path} onChange={update} placeholder="C:\\work\\my-project" required/></label>
          <label>فایل‌ها یا پوشه‌های راهنما <small>هر مسیر در یک خط؛ پوشه‌ها تمام فایل‌های md را اضافه می‌کنند</small><textarea name="guide_paths" value={form.guide_paths} onChange={update} rows="2" placeholder={'AGENTS.md\nC:\\work\\docs'}/></label>
          <div className="row"><label>MCP دانش پروژه <small>اختیاری</small><input name="mcp_server_name" value={form.mcp_server_name} onChange={update} placeholder="dws_project"/></label><label>در صورت خطای MCP<select name="mcp_failure_mode" value={form.mcp_failure_mode} onChange={update}><option value="blocked">متوقف کردن تسک</option><option value="warning">ادامه با هشدار</option></select></label></div>
          <div className="row"><label>شماره تسک<input name="task_id" value={form.task_id} onChange={update} required/></label><label>برنچ مبنا <small>شاخهٔ جدید از این برنچ ساخته می‌شود</small><input name="base_branch" value={form.base_branch} onChange={update} placeholder="main" required/></label></div>
          <label>دستور تست <small>اختیاری</small><input name="test_command" value={form.test_command} onChange={update} placeholder="pytest -q"/></label>
          <label className="test-setup-toggle"><input type="checkbox" name="test_setup_enabled" checked={form.test_setup_enabled} onChange={update}/><span>پیش از اجرای تست، setup دیتابیس محلی را خودکار اجرا کن</span><small>فقط برای TEST_DATABASE_URL روی localhost؛ شامل reset دیتابیس، login با حداکثر ۳ تلاش و اعطای admin است.</small></label>
          <label>درخواست شما<textarea className="request" name="request" value={form.request} onChange={update} required placeholder="دقیقاً بگو چه چیزی باید ساخته یا اصلاح شود…"/></label>
          <button className="primary" disabled={busy||running}><Play size={17}/>{running?'در حال اجرا…':'شروع اجرای تسک'}</button>{notice&&<div className="notice">{notice}</div>}
        </form>
        <section className="card workspace"><div className="card-title"><span>وضعیت اجرا</span><em>02</em></div>
          {sessions.length>0&&<label className="session-picker">گفت‌وگوهای اخیر<select aria-label="گفت‌وگوهای اخیر" value={task?.id||''} onChange={e=>chooseSession(e.target.value)} disabled={busy}>{sessions.map(item=><option key={item.id} value={item.id}>{item.task_id} — {item.step}</option>)}</select></label>}
          {!task?<div className="empty"><div><GitBranch size={36}/></div><h3>هنوز اجرایی شروع نشده</h3><p>اطلاعات تسک را وارد کن تا روند ساخت اینجا نمایش داده شود.</p></div>:<>
            <div className="status"><span className={`status-icon ${task.status}`}>{passed?<CheckCircle2/>:task.status==='stopped'?<Square/>:['failed','blocked'].includes(task.status)?<XCircle/>:<span className="spinner"/>}</span><div><b>{task.step}</b><small><GitBranch size={13}/> {task.branch}</small>{task.mcp_server_name&&<small className={`mcp-state ${task.mcp_status}`}>MCP {task.mcp_server_name}: {task.mcp_message||task.mcp_status}</small>}</div>{running&&task.codex_thread_id&&<button className="stop-run" type="button" onClick={stopTask} disabled={busy}><Square size={13}/> توقف</button>}<mark className={task.status}>{task.status}</mark></div>
            {task.error&&<div className="error">{task.error}</div>}
            <div className="tabs"><button type="button" className={tab==='changes'?'active':''} onClick={()=>setTab('changes')}><FileCode2 size={15}/> تغییرات <b>{task.changed_files.length}</b></button><button type="button" className={tab==='tests'?'active':''} onClick={()=>setTab('tests')}><Terminal size={15}/> تست‌ها</button><button type="button" className={tab==='test-setup'?'active':''} onClick={()=>setTab('test-setup')}><Terminal size={15}/> Setup تست</button><button type="button" className={tab==='summary'?'active':''} onClick={()=>setTab('summary')}><Bot size={15}/> خلاصه</button></div>
            {tab==='test-setup'&&<button type="button" className="run-test-setup" onClick={runTestSetup} disabled={busy||running}><Terminal size={15}/> اجرای setup تست</button>}
            <pre ref={outputRef} className={codexTyping&&task.live_output?'live-console':''} aria-live={codexTyping?'polite':'off'}><DirectionalOutput text={outputText}/></pre>
            <section className="chat" aria-label="Chat with Codex">
              <div className="chat-title"><MessageCircle size={16}/> گفت‌وگو با Codex <small>{task.messages.length} پیام</small></div>
              <div className="chat-history">{task.messages.map((message,index)=><article className={`chat-message ${message.role}`} key={index}><b>{message.role==='user'?'شما':'Codex'}</b><p dir="auto">{message.content}</p></article>)}{(codexTyping||interruptedReply)&&(task.live_response?<article className="chat-message assistant live-response" role="status" aria-live="polite"><b>{codexTyping?'Codex در حال پاسخ است':'پاسخ Codex متوقف شد'}</b><p dir="auto">{task.live_response}</p>{codexTyping&&<span className="typing-dots" aria-hidden="true"><i/><i/><i/></span>}</article>:<div className="chat-typing" role="status" aria-live="polite"><b>Codex در حال پاسخ است</b><span className="typing-dots" aria-hidden="true"><i/><i/><i/></span></div>)}</div>
              <form className="chat-composer" onSubmit={sendMessage}><textarea aria-label="پیام برای Codex" value={chatMessage} onChange={e=>setChatMessage(e.target.value)} onKeyDown={submitChatOnEnter} rows="3" placeholder="ادامه بده، بهبود بده یا سؤال بپرس…" disabled={!task.codex_thread_id||running||busy}/><button type="submit" disabled={!chatMessage.trim()||!task.codex_thread_id||running||busy}><Send size={16}/> ارسال</button></form>
              {!task.codex_thread_id&&<small className="chat-unavailable">پس از تکمیل اجرای اول، گفت‌وگو در همان سشن Codex فعال می‌شود.</small>}
            </section>
             <div className="delivery"><label>پیام commit<input value={task.commit_message||''} disabled={!passed||task.committed} onChange={e=>setTask({...task,commit_message:e.target.value})}/>{task.merge_request_url&&<a className="merge-request-link" href={task.merge_request_url} target="_blank" rel="noreferrer">مشاهده درخواست ادغام</a>}</label><div><button type="button" className="suggest-commit" aria-label="Generate commit message with Codex" disabled={!passed||task.committed||busy||!task.codex_thread_id} onClick={generateCommitMessage}><Sparkles size={14}/>AutoGenerate</button><button type="button" disabled={!passed||task.committed||busy} onClick={()=>action('commit',{message:task.commit_message})}><GitCommit size={16}/>commit</button><button type="button" className="push" disabled={!task.committed||task.pushed||busy} onClick={()=>action('push')}><Upload size={16}/>push</button><button type="button" className="merge-request" disabled={!task.pushed||!!task.merge_request_url||busy} onClick={()=>action('merge-request')}><GitPullRequest size={16}/>{task.merge_request_url?'MR ساخته شد':'Create MR'}</button></div></div>
          </>}
        </section>
      </div>
    </main>
  </div>
}
createRoot(document.getElementById('root')).render(<App/>);
