import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Bot, GitBranch, GitPullRequest, Play, CheckCircle2, XCircle, FileCode2, Terminal, GitCommit, Upload, Sparkles, Moon, Sun, Save, Trash2, MessageCircle, Send, Square, Bell, Copy} from 'lucide-react';
import './styles.css';
import {formatTime} from './timer.js';
import {getInitialTheme, nextTheme} from './theme.js';

const API = import.meta.env.VITE_API_URL || '';
const initial = {project_path:'', guide_paths:'', task_id:'', session_name:'', request:'', base_branch:'main', test_command:'', test_working_directory:'', test_setup_enabled:false, auto_commit:false, auto_generate_commit_message:false, auto_push:false, auto_merge_request:false, mcp_server_name:'', mcp_failure_mode:'warning', git_provider:'gitlab'};
const defaultBaseBranch=path=>/(^|[\\/])dws[\\/]?$/i.test(path.trim())?'sandbox':'main';
const taskIdForBranch=value=>value.trim().replace(/^tasks\//,'');
const taskBranchFor=value=>`tasks/${taskIdForBranch(value)}`;
const apiError=(detail,fallback)=>{
  if(typeof detail==='string'&&detail.trim())return detail;
  if(Array.isArray(detail))return detail.map(item=>{const field=Array.isArray(item?.loc)?item.loc.slice(1).join(' / '):'ورودی';return `${field}: ${item?.msg||'مقدار نامعتبر است'}`}).join(' | ')||fallback;
  if(typeof detail?.message==='string')return detail.message;
  return fallback;
};

function Clock(){
  const [now,setNow]=useState(()=>new Date());
  useEffect(()=>{const timer=setInterval(()=>setNow(new Date()),10);return()=>clearInterval(timer)},[]);
  return <time className="clock" dateTime={now.toISOString()} aria-label="زمان فعلی"><small>زمان فعلی</small><b dir="ltr">{formatTime(now)}</b></time>;
}

function DirectionalOutput({text}){
  return String(text??'').split('\n').map((line,index)=><span className="output-line" dir="auto" key={index}>{line||'\u200b'}</span>);
}

function TodoPanel({task,sessions,todoDraft,setTodoDraft,todoTarget,setTodoTarget,addTodo,sendTodo,removeTodo,busy,running}){
  if(!task)return <section className="todo-modal-card todo-empty"><div className="card-title"><span>کارهای بعدی</span><em>0</em></div><div className="empty"><div><MessageCircle size={30}/></div><h3>صف Todo آماده است</h3><p>پس از شروع اولین تسک، ایده‌ها را اینجا ثبت کن تا به‌ترتیب اجرا شوند.</p></div></section>;
  const pending=task.todos?.filter(todo=>todo.status==='pending').length||0;
  return <section className="todo-modal-card" aria-label="Todo queue"><div className="card-title"><span>کارهای بعدی</span><em>{pending}</em></div><p className="todo-intro">اول سشن، سپس برنچ؛ بعد از تحویل موفق، موارد نیازمند برنچ جدید شروع می‌شوند.</p>
    {!!task.todos?.length&&<div className="todo-list">{task.todos.map(todo=><article key={todo.id} className={`todo-item ${todo.status}`}><div className="todo-content"><p dir="auto">{todo.content}</p><small>{todo.project_path} · {todo.branch} · {todo.session_id||'بدون سشن'}</small>{todo.error&&<small className="todo-error">{todo.error}</small>}</div><div><button type="button" onClick={()=>sendTodo(todo.id)} disabled={busy||running||!task.codex_thread_id||todo.status!=='pending'}>ارسال الآن</button><button className="todo-delete" type="button" onClick={()=>removeTodo(todo.id)} disabled={busy} aria-label="حذف یادداشت"><Trash2 size={14}/></button></div></article>)}</div>}
    <form className="todo-composer" onSubmit={addTodo}><textarea aria-label="یادداشت Todo" value={todoDraft} onChange={e=>setTodoDraft(e.target.value)} rows="3" placeholder="مثلاً: حالت تاریک این صفحه را هم بررسی کن…" disabled={busy}/><button type="submit" disabled={!todoDraft.trim()||busy}>افزودن به صف</button></form>
    <div className="todo-target"><label>سشن مقصد<select value={todoTarget.session_id} onChange={e=>setTodoTarget(current=>({...current,session_id:e.target.value}))}><option value="">بدون سشن مشخص</option>{sessions.map(item=><option key={item.id} value={item.id}>{item.session_name||item.task_id}</option>)}</select></label><label>پروژه<input value={todoTarget.project_path} onChange={e=>setTodoTarget(current=>({...current,project_path:e.target.value}))}/></label><label>برنچ<input value={todoTarget.branch} onChange={e=>setTodoTarget(current=>({...current,branch:e.target.value}))}/></label></div>
    {running&&<small className="todo-hint">Todo ذخیره می‌شود و با اتمام زنجیرهٔ فعلی، خودکار ادامه می‌دهد.</small>}
  </section>;
}

function App(){
  const [form,setForm]=useState(initial), [task,setTask]=useState(null), [busy,setBusy]=useState(false), [tab,setTab]=useState('changes'), [notice,setNotice]=useState(''), [commitRetry,setCommitRetry]=useState(null), [chatMessage,setChatMessage]=useState(''), [todoDraft,setTodoDraft]=useState(''), [todoTarget,setTodoTarget]=useState({session_id:'',project_path:'',branch:''}), [showTodoModal,setShowTodoModal]=useState(false), [copiedMessage,setCopiedMessage]=useState('');
  const [profiles,setProfiles]=useState([]), [selectedProfile,setSelectedProfile]=useState(''), [sessions,setSessions]=useState([]);
  const [branchData,setBranchData]=useState({current:'',branches:[]}), [branchesLoading,setBranchesLoading]=useState(false);
  const [codexStatus,setCodexStatus]=useState(null), [codexStatusLoading,setCodexStatusLoading]=useState(false);
  const [startupDefaults,setStartupDefaults]=useState(initial);
  const [theme,setTheme]=useState(()=>getInitialTheme(localStorage,window.matchMedia('(prefers-color-scheme: dark)').matches));
  const [windowsNotifications,setWindowsNotifications]=useState(()=>localStorage.getItem('taskloom-windows-notifications')==='enabled'&&typeof Notification!=='undefined'&&Notification.permission==='granted');
  const outputRef=useRef(null);
  const notificationTaskRef=useRef(null);
  const update=e=>{const {name,value,type,checked}=e.target;const next=type==='checkbox'?checked:value;if(name==='project_path')setBranchData({current:'',branches:[]});if(name!=='project_path'||!startupDefaults.project_path||value===startupDefaults.project_path){setForm({...form,[name]:next,...(name==='project_path'?{task_id:''}:{})});return}setForm(current=>({...current,project_path:value,task_id:'',guide_paths:current.guide_paths===startupDefaults.guide_paths?'':current.guide_paths,base_branch:current.base_branch===startupDefaults.base_branch?defaultBaseBranch(value):current.base_branch,test_command:current.test_command===startupDefaults.test_command?'':current.test_command,test_working_directory:current.test_working_directory===startupDefaults.test_working_directory?'':current.test_working_directory,mcp_server_name:current.mcp_server_name===startupDefaults.mcp_server_name?'':current.mcp_server_name,mcp_failure_mode:current.mcp_failure_mode===startupDefaults.mcp_failure_mode?'warning':current.mcp_failure_mode}))};
  function rememberTask(next){setTask(next);setSessions(current=>[next,...current.filter(item=>item.id!==next.id)]);localStorage.setItem('taskloom-active-session',next.id)}
  useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('taskloom-theme',theme)},[theme]);
  useEffect(()=>{fetch(`${API}/api/defaults`).then(async r=>{if(!r.ok)throw Error('خواندن پیش‌فرض‌ها ناموفق بود');const defaults=await r.json();const loaded={...initial,project_path:defaults.project_path||'',guide_paths:(defaults.guide_paths||[]).join('\n'),base_branch:defaults.base_branch||'main',test_command:defaults.test_command||'',test_working_directory:defaults.test_working_directory||'',test_setup_enabled:!!defaults.test_setup_enabled,auto_commit:!!defaults.auto_commit,auto_generate_commit_message:!!defaults.auto_generate_commit_message,auto_push:!!defaults.auto_push,auto_merge_request:!!defaults.auto_merge_request,mcp_server_name:defaults.mcp_server_name||'',mcp_failure_mode:defaults.mcp_failure_mode||'warning'};setStartupDefaults(loaded);setForm(current=>current.project_path?current:{...current,...loaded});if(defaults.project_path)loadBranches(defaults.project_path,true)}).catch(e=>setNotice(e.message))},[]);
  useEffect(()=>{fetch(`${API}/api/profiles`).then(async r=>{if(!r.ok)throw Error('خواندن پروفایل‌ها ناموفق بود');setProfiles(await r.json())}).catch(e=>setNotice(e.message))},[]);
  useEffect(()=>{refreshCodexStatus()},[]);
  useEffect(()=>{fetch(`${API}/api/tasks`).then(async r=>{if(!r.ok)throw Error('خواندن سشن‌ها ناموفق بود');const items=await r.json();setSessions(items);const active=items.find(item=>item.id===localStorage.getItem('taskloom-active-session'))||items[0];if(active)setTask(active)}).catch(e=>setNotice(e.message))},[]);
  useEffect(()=>{if(!task||['passed','failed','blocked','stopped'].includes(task.status)||typeof EventSource==='undefined')return;const events=new EventSource(`${API}/api/tasks/${task.id}/events`);events.onmessage=e=>{const next=JSON.parse(e.data);rememberTask(next);if(['passed','failed','blocked','stopped'].includes(next.status))events.close()};events.onerror=()=>events.close();return()=>events.close()},[task?.id,task?.status]);
  useEffect(()=>{ if(!task || ['passed','failed','blocked','stopped'].includes(task.status)) return; const timer=setInterval(async()=>{const r=await fetch(`${API}/api/tasks/${task.id}`); if(r.ok)rememberTask(await r.json())},1400); return()=>clearInterval(timer)},[task?.id,task?.status]);
  useEffect(()=>{const panel=outputRef.current;if(panel&&task&&['queued','running'].includes(task.status))panel.scrollTop=panel.scrollHeight},[task?.live_output,task?.live_response]);
  useEffect(()=>{document.querySelectorAll('.chat-history').forEach(history=>history.scrollTo({top:history.scrollHeight,behavior:'smooth'}))},[task?.id,task?.messages?.length,task?.live_response,task?.status]);
  useEffect(()=>{if(task)setTodoTarget({session_id:task.id,project_path:task.project_path,branch:task.branch})},[task?.id]);
  useEffect(()=>{const previous=notificationTaskRef.current,terminal=['passed','failed','blocked','stopped'].includes(task?.status),sameTask=!!task&&previous?.id===task.id,newRun=sameTask&&['passed','failed','blocked','stopped'].includes(previous.status)&&!terminal,replyNotified=newRun?false:previous?.replyNotified,newMessages=task?.messages?.slice(sameTask?previous.messageCount:task?.messages?.length)||[],reply=[...newMessages].reverse().find(message=>message.role==='assistant'),finishedWithoutReply=sameTask&&!['passed','failed','blocked','stopped'].includes(previous.status)&&terminal&&!replyNotified;if(windowsNotifications&&typeof Notification!=='undefined'&&Notification.permission==='granted'&&(reply||finishedWithoutReply)){const summary=(reply?.content||task.summary||task.error||task.step||'پاسخ Codex آماده است').replace(/\s+/g,' ').trim();new Notification(reply?'پاسخ Codex آماده است':'اجرای Codex تمام شد',{body:summary.slice(0,260),tag:`taskloom-${task.id}`})}notificationTaskRef.current=task?{id:task.id,status:task.status,messageCount:task.messages.length,replyNotified:replyNotified||!!reply}:null},[task?.id,task?.status,task?.summary,task?.error,task?.messages?.length,windowsNotifications]);
  async function start(e){e.preventDefault();setBusy(true);setNotice('');try{const task_id=taskIdForBranch(form.task_id)||`session-${Date.now().toString(36)}`,session_name=form.session_name.trim()||task_id;const body={...form,task_id,session_name,guide_paths:form.guide_paths.split('\n').map(x=>x.trim()).filter(Boolean),test_command:form.test_command||null,test_working_directory:form.test_working_directory||null,mcp_server_name:form.mcp_server_name.trim()||null};const r=await fetch(`${API}/api/tasks`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(apiError(d.detail,'شروع تسک ناموفق بود'));rememberTask(d)}catch(err){setNotice(err.message)}finally{setBusy(false)}}
  async function action(kind,body,retry=false){setBusy(true);setNotice(retry?'در حال اجرای git add . و تلاش مجدد برای commit…':'');try{const r=await fetch(`${API}/api/tasks/${task.id}/${kind}`,{method:'POST',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(apiError(d.detail,'انجام عملیات ناموفق بود'));rememberTask(d.task);if(kind==='commit')setCommitRetry(null);setNotice({commit:'تغییرات با موفقیت commit شدند.',push:'برنچ با موفقیت push شد.','merge-request':'درخواست ادغام با موفقیت ساخته شد.'}[kind])}catch(e){if(kind==='commit'){setCommitRetry({taskId:task.id,message:body?.message||task.commit_message||'',error:e.message});setNotice(retry?`تلاش مجدد برای commit هم ناموفق بود و نیاز به بازبینی انسانی دارد: ${e.message}`:`commit ناموفق بود. برای stage دوباره و تلاش مجدد، دکمهٔ «تلاش مجدد با git add .» را بزن.`)}else setNotice(e.message)}finally{setBusy(false)}}
  function retryCommit(){if(task)action('commit',{message:task.commit_message||commitRetry?.message||''},true)}
  async function runTestSetup(){if(!task)return;if(!window.confirm('دیتابیس تست محلی و قابل حذف است؟ این عملیات داده‌های آن را reset می‌کند.'))return;setBusy(true);setNotice('');try{const r=await fetch(`${API}/api/test-setup`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project_path:task.project_path,confirm_test_database:true})});const d=await r.json();if(!r.ok)throw Error(apiError(d.detail,'اجرای setup تست ناموفق بود'));setTask(current=>({...current,test_setup_output:d.output}));setTab('test-setup');setNotice('Setup محیط تست با موفقیت انجام شد.')}catch(e){setNotice(e.message)}finally{setBusy(false)}}
  async function generateCommitMessage(){if(!task?.codex_thread_id)return;setBusy(true);setNotice('');try{const r=await fetch(`${API}/api/tasks/${task.id}/commit-message`,{method:'POST'});const d=await r.json();if(!r.ok)throw Error(apiError(d.detail,'ساخت پیام commit ناموفق بود'));setTask(current=>({...current,commit_message:d.message}));setNotice('پیام commit پیشنهادی Codex در فیلد قرار گرفت.')}catch(e){setNotice(e.message)}finally{setBusy(false)}}
  async function sendMessage(e){e.preventDefault();const message=chatMessage.trim();if(!message||!task?.codex_thread_id)return;setBusy(true);setNotice('');try{const r=await fetch(`${API}/api/tasks/${task.id}/messages`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message})});const d=await r.json();if(!r.ok)throw Error(apiError(d.detail,'ارسال پیام ناموفق بود'));rememberTask(d);setChatMessage('');setTab('summary')}catch(err){setNotice(err.message)}finally{setBusy(false)}}
  async function addTodo(e){e.preventDefault();const content=todoDraft.trim();if(!content||!task)return;setBusy(true);setNotice('');try{const r=await fetch(`${API}/api/tasks/${task.id}/todos`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content,...todoTarget})});const d=await r.json();if(!r.ok)throw Error(apiError(d.detail,'ذخیره‌کردن Todo ناموفق بود'));rememberTask(d);setTodoDraft('')}catch(err){setNotice(err.message)}finally{setBusy(false)}}
  async function removeTodo(todoId){if(!task)return;setBusy(true);setNotice('');try{const r=await fetch(`${API}/api/tasks/${task.id}/todos/${todoId}`,{method:'DELETE'});const d=await r.json();if(!r.ok)throw Error(apiError(d.detail,'حذف Todo ناموفق بود'));rememberTask(d)}catch(err){setNotice(err.message)}finally{setBusy(false)}}
  async function sendTodo(todoId){if(!task)return;setBusy(true);setNotice('');try{const r=await fetch(`${API}/api/tasks/${task.id}/todos/${todoId}/send`,{method:'POST'});const d=await r.json();if(!r.ok)throw Error(apiError(d.detail,'ارسال Todo ناموفق بود'));rememberTask(d);setTab('summary')}catch(err){setNotice(err.message)}finally{setBusy(false)}}
  async function stopTask(){if(!task)return;setBusy(true);setNotice('');try{const r=await fetch(`${API}/api/tasks/${task.id}/stop`,{method:'POST'});const d=await r.json();if(!r.ok)throw Error(apiError(d.detail,'توقف Codex ناموفق بود'));rememberTask(d);setTab('summary');setNotice(d.codex_thread_id?'Codex متوقف شد؛ اصلاحیه را در کادر گفتگو بفرست.':'اجرا پیش از ساخته‌شدن سشن متوقف شد؛ برای ادامه یک تسک جدید شروع کن.')}catch(err){setNotice(err.message)}finally{setBusy(false)}}
  async function loadBranches(projectPath=form.project_path,silent=false){const project=projectPath.trim();if(!project){setBranchData({current:'',branches:[]});return}setBranchesLoading(true);if(!silent)setNotice('');try{const r=await fetch(`${API}/api/branches?project_path=${encodeURIComponent(project)}`);const d=await r.json();if(!r.ok)throw Error(apiError(d.detail,'خواندن برنچ‌ها ناموفق بود'));setBranchData(d);if(d.current.startsWith('tasks/'))setForm(current=>current.task_id?current:{...current,task_id:taskIdForBranch(d.current)})}catch(err){if(!silent)setNotice(err.message)}finally{setBranchesLoading(false)}}
  async function switchBranch(){const task_id=taskIdForBranch(form.task_id);if(!task_id){setNotice('شماره تسک را وارد یا از فهرست انتخاب کن.');return}setBusy(true);setNotice('');try{const r=await fetch(`${API}/api/branches/switch`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project_path:form.project_path,branch:taskBranchFor(task_id)})});const d=await r.json();if(!r.ok)throw Error(apiError(d.detail,'سوییچ برنچ ناموفق بود'));setBranchData(d);setForm(current=>({...current,task_id:taskIdForBranch(d.current)}));setNotice(d.message)}catch(err){setNotice(err.message)}finally{setBusy(false)}}
  async function refreshCodexStatus(){setCodexStatusLoading(true);try{const r=await fetch(`${API}/api/codex/status`);const d=await r.json();if(!r.ok)throw Error(apiError(d.detail,'خواندن وضعیت Codex ناموفق بود'));setCodexStatus(d)}catch(err){setNotice(err.message)}finally{setCodexStatusLoading(false)}}
  async function toggleWindowsNotifications(){if(typeof Notification==='undefined'){setNotice('مرورگر شما اعلان ویندوز را پشتیبانی نمی‌کند.');return}if(windowsNotifications){localStorage.removeItem('taskloom-windows-notifications');setWindowsNotifications(false);return}const permission=await Notification.requestPermission();if(permission==='granted'){localStorage.setItem('taskloom-windows-notifications','enabled');setWindowsNotifications(true)}else setNotice('مجوز اعلان ویندوز داده نشد؛ آن را از تنظیمات مرورگر فعال کنید.')}
  function submitChatOnEnter(e){if(e.key!=='Enter'||e.shiftKey||e.nativeEvent.isComposing)return;e.preventDefault();e.currentTarget.form?.requestSubmit()}
  async function chooseSession(id){if(!id){setTask(null);localStorage.removeItem('taskloom-active-session');return}setBusy(true);setNotice('');try{const r=await fetch(`${API}/api/tasks/${id}`);const d=await r.json();if(!r.ok)throw Error(apiError(d.detail,'خواندن سشن ناموفق بود'));rememberTask(d)}catch(err){setNotice(err.message)}finally{setBusy(false)}}
  function newSession(){setTask(null);setChatMessage('');setTodoDraft('');setTab('changes');localStorage.removeItem('taskloom-active-session');setForm(current=>({...current,task_id:'',session_name:'',request:''}))}
  async function renameSession(){if(!task)return;const session_name=(window.prompt('نام جدید سشن:',task.session_name||task.task_id)||'').trim();if(!session_name)return;setBusy(true);setNotice('');try{const r=await fetch(`${API}/api/tasks/${task.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({session_name})});const d=await r.json();if(!r.ok)throw Error(apiError(d.detail,'تغییر نام سشن ناموفق بود'));rememberTask(d)}catch(err){setNotice(err.message)}finally{setBusy(false)}}
  async function deleteSession(){if(!task||!['passed','failed','blocked','stopped'].includes(task.status))return;const name=task.session_name||task.task_id;if(!window.confirm(`سشن «${name}» برای همیشه حذف شود؟`))return;setBusy(true);setNotice('');try{const r=await fetch(`${API}/api/tasks/${task.id}`,{method:'DELETE'});if(!r.ok){const d=await r.json();throw Error(apiError(d.detail,'حذف سشن ناموفق بود'))}const remaining=sessions.filter(item=>item.id!==task.id),next=remaining[0]||null;setSessions(remaining);setTask(next);setChatMessage('');setTodoDraft('');setTab('changes');if(next)localStorage.setItem('taskloom-active-session',next.id);else localStorage.removeItem('taskloom-active-session');setNotice('سشن حذف شد.')}catch(err){setNotice(err.message)}finally{setBusy(false)}}
  async function copyMessage(content,key){try{if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(content);else{const textarea=document.createElement('textarea');textarea.value=content;textarea.style.cssText='position:fixed;opacity:0';document.body.append(textarea);textarea.select();if(!document.execCommand('copy'))throw Error('Copy failed');textarea.remove()}setCopiedMessage(key);window.setTimeout(()=>setCopiedMessage(current=>current===key?'':current),1600)}catch{setNotice('کپی پیام ناموفق بود.')}}
  function chooseProfile(name){setSelectedProfile(name);const profile=profiles.find(item=>item.name===name);if(profile){setBranchData({current:'',branches:[]});setForm(current=>({...current,task_id:'',project_path:profile.project_path,guide_paths:profile.guide_paths.join('\n'),base_branch:profile.base_branch||defaultBaseBranch(profile.project_path),test_command:profile.test_command||'',test_working_directory:profile.test_working_directory||'',test_setup_enabled:!!profile.test_setup_enabled,auto_commit:!!profile.auto_commit,auto_generate_commit_message:!!profile.auto_generate_commit_message,auto_push:!!profile.auto_push,auto_merge_request:!!profile.auto_merge_request,mcp_server_name:profile.mcp_server_name||'',mcp_failure_mode:profile.mcp_failure_mode||'warning',git_provider:profile.git_provider||'auto'}));loadBranches(profile.project_path,true)}}
  async function saveProfile(){const name=(selectedProfile||window.prompt('نام پروفایل پروژه را وارد کنید:')||'').trim();if(!name)return;setBusy(true);setNotice('');try{const profile={name,project_path:form.project_path,guide_paths:form.guide_paths.split('\n').map(x=>x.trim()).filter(Boolean),base_branch:form.base_branch.trim(),test_command:form.test_command||null,test_working_directory:form.test_working_directory||null,test_setup_enabled:form.test_setup_enabled,auto_commit:form.auto_commit,auto_generate_commit_message:form.auto_generate_commit_message,auto_push:form.auto_push,auto_merge_request:form.auto_merge_request,mcp_server_name:form.mcp_server_name.trim()||null,mcp_failure_mode:form.mcp_failure_mode};const r=await fetch(`${API}/api/profiles/${encodeURIComponent(name)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(profile)});const d=await r.json();if(!r.ok)throw Error(apiError(d.detail,'ذخیره پروفایل ناموفق بود'));setProfiles(current=>[...current.filter(item=>item.name!==name),d].sort((a,b)=>a.name.localeCompare(b.name)));setSelectedProfile(name);setNotice('پروفایل پروژه ذخیره شد.')}catch(e){setNotice(e.message)}finally{setBusy(false)}}
  async function removeProfile(){if(!selectedProfile)return;setBusy(true);setNotice('');try{const r=await fetch(`${API}/api/profiles/${encodeURIComponent(selectedProfile)}`,{method:'DELETE'});if(!r.ok){const d=await r.json();throw Error(apiError(d.detail,'حذف پروفایل ناموفق بود'))}setProfiles(current=>current.filter(item=>item.name!==selectedProfile));setSelectedProfile('');setNotice('پروفایل حذف شد.')}catch(e){setNotice(e.message)}finally{setBusy(false)}}
  const running=task&&!['passed','failed','blocked','stopped'].includes(task.status), passed=task?.status==='passed', codexTyping=task&&['queued','running'].includes(task.status), interruptedReply=task?.status==='stopped'&&task.live_response;
  const changeOutput=codexTyping&&task.live_output?task.live_output:(task?.diff||'در انتظار تغییرات…');
  const outputText=tab==='changes'?changeOutput:tab==='tests'?(task.test_output||'تست‌ها هنوز اجرا نشده‌اند…'):tab==='test-setup'?(task.test_setup_output||'هنوز setup تست اجرا نشده است.'):(task.live_response||task.summary||task.logs.join('\n')||'در حال تحلیل…');
  const codexRateLimits=Object.values(codexStatus?.rate_limits?.rateLimitsByLimitId||{}), visibleCodexRateLimits=codexRateLimits.length?codexRateLimits:[codexStatus?.rate_limits?.rateLimits].filter(Boolean), codexUsage=codexStatus?.usage?.dailyUsageBuckets||[], activeCodexModel=codexStatus?.models?.find(model=>model.isDefault)||codexStatus?.models?.[0];
  const number=value=>new Intl.NumberFormat('fa-IR').format(value||0), resetAt=value=>value?new Date(value*1000).toLocaleString('fa-IR',{dateStyle:'short',timeStyle:'short'}):'—';
  const gitProviderControl=<label className="git-provider">Git hosting<select name="git_provider" value={form.git_provider} onChange={update}><option value="gitlab">GitLab</option><option value="github">GitHub</option><option value="auto">Auto</option></select></label>;
  return <div className="app" dir="rtl">
    <header><div className="brand"><span className="logo"><Sparkles size={20}/></span><div><b>Taskloom</b><small>Codex delivery console</small></div></div><div className="header-status"><button className="todo-open" type="button" onClick={()=>setShowTodoModal(true)}>کارهای بعدی {task?.todos?.filter(todo=>todo.status==='pending').length?`(${task.todos.filter(todo=>todo.status==='pending').length})`:''}</button><Clock/><button className="theme-toggle" type="button" onClick={()=>setTheme(nextTheme(theme))} aria-label={theme==='dark'?'فعال‌کردن تم روشن':'فعال‌کردن تم تاریک'} aria-pressed={theme==='dark'}>{theme==='dark'?<Sun size={16}/>:<Moon size={16}/>}<span>{theme==='dark'?'روشن':'دارک'}</span></button><div className="online"><i/> Codex محلی</div></div></header>
    <main>
      {/*<section className="intro"><div><span className="eyebrow"><Bot size={15}/></span><p></p></div><div className="orb"><Bot size={46}/></div></section>*/}
      <div className="grid">
        <form className="card form" onSubmit={start}>{gitProviderControl}
          <div className="card-title"><span>تعریف تسک</span><em>01</em></div>
          <div className="profile-picker"><select aria-label="پروفایل پروژه" value={selectedProfile} onChange={e=>chooseProfile(e.target.value)}><option value="">پروفایل پروژه…</option>{profiles.map(profile=><option key={profile.name} value={profile.name}>{profile.name}</option>)}</select><button type="button" onClick={saveProfile} disabled={busy||!form.project_path} title="ذخیره پروفایل"><Save size={16}/><span>{selectedProfile?'به‌روزرسانی':'ذخیره'}</span></button><button className="danger" type="button" onClick={removeProfile} disabled={busy||!selectedProfile} title="حذف پروفایل" aria-label="حذف پروفایل"><Trash2 size={16}/><span>حذف</span></button></div>
          <label>آدرس پروژه <small>با تغییر مسیر، راهنما، تست، MCP و برنچ مبنای پیش‌فرض همان پروژه تنظیم می‌شوند</small><input name="project_path" value={form.project_path} onChange={update} placeholder="C:\\work\\my-project" required/></label>
          <section className="branch-manager" aria-label="مدیریت برنچ‌ها"><div className="branch-manager-title"><GitBranch size={16}/> تسک و برنچ <button type="button" onClick={()=>loadBranches()} disabled={busy||branchesLoading||!form.project_path.trim()}>{branchesLoading?'در حال خواندن…':'به‌روزرسانی'}</button></div><p>برنچ فعال: <b dir="ltr">{branchData.current||'—'}</b></p><div className="branch-controls"><input aria-label="شماره تسک برای سوییچ یا ساخت برنچ" name="task_id" list="task-branches" value={form.task_id} onChange={update} placeholder="podw-202"/><datalist id="task-branches">{branchData.branches.filter(branch=>branch.name.startsWith('tasks/')).map(branch=><option key={branch.name} value={taskIdForBranch(branch.name)} label={`${branch.name}${!branch.local&&branch.remote?' (origin)':''}`}/>)}</datalist><button type="button" onClick={switchBranch} disabled={busy||branchesLoading||!form.project_path.trim()||!form.task_id.trim()}>{busy?'در حال انجام…':'ساخت یا سوییچ'}</button></div><small>همین‌جا شمارهٔ تسک را بنویس یا از فهرست انتخاب کن. برای <b dir="ltr">podw-202</b> برنچ <b dir="ltr">tasks/podw-202</b> در صورت وجود checkout و در غیر این صورت از برنچ فعلی ساخته می‌شود. هیچ reset یا stashی انجام نمی‌شود.</small></section>
          <label>فایل‌ها یا پوشه‌های راهنما <small>هر مسیر در یک خط؛ پوشه‌ها تمام فایل‌های md را اضافه می‌کنند</small><textarea name="guide_paths" value={form.guide_paths} onChange={update} rows="2" placeholder={'AGENTS.md\nC:\\work\\docs'}/></label>
          <div className="row"><label>MCP دانش پروژه <small>اختیاری</small><input name="mcp_server_name" value={form.mcp_server_name} onChange={update} placeholder="dws_project"/></label><label>در صورت خطای MCP<select name="mcp_failure_mode" value={form.mcp_failure_mode} onChange={update}><option value="blocked">متوقف کردن تسک</option><option value="warning">ادامه با هشدار</option></select></label></div>
          <label>نام سشن <small>اختیاری؛ مثلاً change color یا j</small><input name="session_name" value={form.session_name} onChange={update} placeholder="change color"/></label>
          <label>برنچ مبنا <small>شاخهٔ جدید از این برنچ ساخته می‌شود</small><input name="base_branch" value={form.base_branch} onChange={update} placeholder="main" required/></label>
          <div className="row"><label>دستور تست <small>اختیاری</small><input name="test_command" value={form.test_command} onChange={update} placeholder="pytest -q"/></label><label>پوشهٔ کاری تست <small>نسبت به ریشهٔ پروژه</small><input name="test_working_directory" value={form.test_working_directory} onChange={update} placeholder="backend"/></label></div>
          <details className="test-setup"><summary>Setup تست</summary><label className="test-setup-toggle"><input type="checkbox" name="test_setup_enabled" checked={form.test_setup_enabled} onChange={update}/><span>پیش از اجرای تست، setup دیتابیس محلی را خودکار اجرا کن</span><small>فقط برای TEST_DATABASE_URL روی localhost؛ شامل reset دیتابیس، login با حداکثر ۳ تلاش و اعطای admin است.</small></label></details>
          <section className="auto-delivery" aria-label="تحویل خودکار"><b>تحویل خودکار و اجرای Todo بعدی</b><label><input type="checkbox" checked={form.auto_commit} onChange={e=>setForm(current=>({...current,auto_commit:e.target.checked,auto_generate_commit_message:e.target.checked?current.auto_generate_commit_message:false,auto_push:e.target.checked?current.auto_push:false,auto_merge_request:e.target.checked?current.auto_merge_request:false}))}/><span>بعد از پاس‌شدن تست‌ها، خودکار commit کن</span></label><label><input type="checkbox" checked={form.auto_generate_commit_message} disabled={!form.auto_commit} onChange={e=>setForm(current=>({...current,auto_generate_commit_message:e.target.checked}))}/><span>پیش از commit، پیام را با Codex خودکار تولید کن</span></label><label><input type="checkbox" checked={form.auto_push} disabled={!form.auto_commit} onChange={e=>setForm(current=>({...current,auto_push:e.target.checked,auto_merge_request:e.target.checked?current.auto_merge_request:false}))}/><span>بعدش push کن</span></label><label><input type="checkbox" checked={form.auto_merge_request} disabled={!form.auto_push} onChange={e=>setForm(current=>({...current,auto_merge_request:e.target.checked}))}/><span>بعدش MR بساز</span></label><small>صف Todo فقط پس از موفقیت تست و همهٔ مرحله‌های انتخاب‌شده ادامه پیدا می‌کند.</small></section>
          <label>درخواست شما<textarea className="request" name="request" value={form.request} onChange={update} required placeholder="دقیقاً بگو چه چیزی باید ساخته یا اصلاح شود…"/></label>
          <button className="primary" disabled={busy||running}><Play size={17}/>{running?'در حال اجرا…':'شروع اجرای تسک'}</button>{notice&&<div className="notice">{notice}</div>}
        </form>
        <section className="card workspace"><div className="card-title"><span>وضعیت اجرا</span><em>02</em></div>
          <div className="session-controls"><label className="session-picker">گفت‌وگوهای اخیر<select aria-label="گفت‌وگوهای اخیر" value={task?.id||''} onChange={e=>chooseSession(e.target.value)} disabled={busy}><option value="">سشن جدید…</option>{sessions.map(item=><option key={item.id} value={item.id}>{item.session_name||item.task_id} — {item.step}</option>)}</select></label><button className="new-session" type="button" onClick={newSession} disabled={busy}>سشن جدید</button>{task&&<button className="rename-session" type="button" onClick={renameSession} disabled={busy}>تغییر نام</button>}{task&&<button className="delete-session" type="button" onClick={deleteSession} disabled={busy||running} title={running?'ابتدا اجرای سشن را متوقف کن':'حذف سشن'} aria-label="حذف سشن"><Trash2 size={14}/><span>حذف</span></button>}</div>
          {!task?<div className="empty"><div><GitBranch size={36}/></div><h3>هنوز اجرایی شروع نشده</h3><p>اطلاعات تسک را وارد کن تا روند ساخت اینجا نمایش داده شود.</p></div>:<>
            {task.error&&<div className="error"><span>{task.error}</span>{task.status==='failed'&&task.test_output&&<details className="test-error-details"><summary>مشاهده جزئیات</summary><p>خروجی کامل آخرین اجرای تست:</p><pre aria-label="خروجی کامل خطای تست"><DirectionalOutput text={task.test_output}/></pre></details>}</div>}
            <details className="execution-details"><summary>جزئیات اجرا و تغییرات</summary>
            <div className="status"><span className={`status-icon ${task.status}`}>{passed?<CheckCircle2/>:task.status==='stopped'?<Square/>:['failed','blocked'].includes(task.status)?<XCircle/>:<span className="spinner"/>}</span><div><b>{task.step}</b><small><GitBranch size={13}/> {task.branch}</small>{task.mcp_server_name&&<small className={`mcp-state ${task.mcp_status}`}>MCP {task.mcp_server_name}: {task.mcp_message||task.mcp_status}</small>}</div>{running&&task.codex_thread_id&&<button className="stop-run" type="button" onClick={stopTask} disabled={busy}><Square size={13}/> توقف</button>}<mark className={task.status}>{task.status}</mark></div>
            <div className="tabs"><button type="button" className={tab==='changes'?'active':''} onClick={()=>setTab('changes')}><FileCode2 size={15}/> تغییرات <b>{task.changed_files.length}</b></button><button type="button" className={tab==='tests'?'active':''} onClick={()=>setTab('tests')}><Terminal size={15}/> تست‌ها</button><button type="button" className={tab==='test-setup'?'active':''} onClick={()=>setTab('test-setup')}><Terminal size={15}/> Setup تست</button><button type="button" className={tab==='summary'?'active':''} onClick={()=>setTab('summary')}><Bot size={15}/> خلاصه</button></div>
            {tab==='test-setup'&&<button type="button" className="run-test-setup" onClick={runTestSetup} disabled={busy||running}><Terminal size={15}/> اجرای setup تست</button>}
            <pre ref={outputRef} className={codexTyping&&task.live_output?'live-console':''} aria-live={codexTyping?'polite':'off'}><DirectionalOutput text={outputText}/></pre>
            </details>
            {false&&<section className="todo" aria-label="Todo queue">
              <div className="todo-title"><span>Todo</span><small>{task.todos?.filter(todo=>todo.status==='pending').length||0} در صف</small></div>
              <p>یادداشت‌ها به‌ترتیب ثبت اجرا می‌شوند. مقصد هر مورد: سشن، سپس برنچ و در آخر پروژه است.</p>
              {!!task.todos?.length&&<div className="todo-list">{task.todos.map(todo=><article key={todo.id} className={`todo-item ${todo.status}`}><div className="todo-content"><p dir="auto">{todo.content}</p><small>{todo.project_path} · {todo.branch} · {todo.session_id||'بدون سشن'}</small>{todo.error&&<small className="todo-error">{todo.error}</small>}</div><div><button type="button" onClick={()=>sendTodo(todo.id)} disabled={busy||running||!task.codex_thread_id||todo.status!=='pending'}>همین حالا ارسال</button><button className="todo-delete" type="button" onClick={()=>removeTodo(todo.id)} disabled={busy} aria-label="حذف یادداشت"><Trash2 size={14}/></button></div></article>)}</div>}
              <form className="todo-composer" onSubmit={addTodo}><textarea aria-label="یادداشت Todo" value={todoDraft} onChange={e=>setTodoDraft(e.target.value)} rows="2" placeholder="مثلاً: بعداً حالت تاریک این صفحه را هم بررسی کن…" disabled={busy}/><button type="submit" disabled={!todoDraft.trim()||busy}>افزودن به صف</button></form>
              <div className="todo-target"><label>سشن مقصد<select value={todoTarget.session_id} onChange={e=>setTodoTarget(current=>({...current,session_id:e.target.value}))}><option value="">بدون سشن مشخص</option>{sessions.map(item=><option key={item.id} value={item.id}>{item.session_name||item.task_id}</option>)}</select></label><label>پروژه<input value={todoTarget.project_path} onChange={e=>setTodoTarget(current=>({...current,project_path:e.target.value}))}/></label><label>برنچ<input value={todoTarget.branch} onChange={e=>setTodoTarget(current=>({...current,branch:e.target.value}))}/></label></div>
              {running&&<small className="todo-hint">مورد ثبت می‌شود و بعد از پایان اجرای فعلی، خودکار سراغ اولین Todo می‌رود.</small>}
            </section>}
            <section className="chat" aria-label="Chat with Codex">
              <div className="chat-title"><MessageCircle size={16}/> گفت‌وگو با Codex <small>{task.messages.length} پیام</small></div>
              <div className="chat-history">{task.messages.map((message,index)=>{const key=`${task.id}-${index}`;return <article className={`chat-message ${message.role}`} key={key}><b>{message.role==='user'?'شما':'Codex'}</b><button className="chat-copy" type="button" onClick={()=>copyMessage(message.content,key)} aria-label={`کپی پیام ${message.role==='user'?'شما':'Codex'}`} title="کپی پیام">{copiedMessage===key?'کپی شد':<Copy size={13}/>}</button><p dir="auto">{message.content}</p></article>})}{(codexTyping||interruptedReply)&&(task.live_response?<article className="chat-message assistant live-response" role="status" aria-live="polite"><b>{codexTyping?'Codex در حال پاسخ است':'پاسخ Codex متوقف شد'}</b><button className="chat-copy" type="button" onClick={()=>copyMessage(task.live_response,`live-${task.id}`)} aria-label="کپی پاسخ Codex" title="کپی پاسخ Codex">{copiedMessage===`live-${task.id}`?'کپی شد':<Copy size={13}/>}</button><p dir="auto">{task.live_response}</p>{codexTyping&&<span className="typing-dots" aria-hidden="true"><i/><i/><i/></span>}</article>:<div className="chat-typing" role="status" aria-live="polite"><b>Codex در حال پاسخ است</b><span className="typing-dots" aria-hidden="true"><i/><i/><i/></span></div>)}</div>
              <form className="chat-composer" onSubmit={sendMessage}><textarea aria-label="پیام برای Codex" value={chatMessage} onChange={e=>setChatMessage(e.target.value)} onKeyDown={submitChatOnEnter} rows="3" placeholder="ادامه بده، بهبود بده یا سؤال بپرس…" disabled={!task.codex_thread_id||running||busy}/><button type="submit" disabled={!chatMessage.trim()||!task.codex_thread_id||running||busy}><Send size={16}/> ارسال</button></form>
              {!task.codex_thread_id&&<small className="chat-unavailable">پس از تکمیل اجرای اول، گفت‌وگو در همان سشن Codex فعال می‌شود.</small>}
            </section>
            <div className="delivery"><label>پیام commit<input value={task.commit_message||''} disabled={!passed||task.committed} onChange={e=>setTask({...task,commit_message:e.target.value})}/>{task.merge_request_url&&<a className="merge-request-link" href={task.merge_request_url} target="_blank" rel="noreferrer">مشاهده درخواست ادغام</a>}</label><div><button type="button" className="suggest-commit" aria-label="Generate commit message with Codex" disabled={!passed||task.committed||busy||!task.codex_thread_id} onClick={generateCommitMessage}><Sparkles size={14}/>AutoGenerate</button><button type="button" disabled={!passed||task.committed||busy} onClick={()=>action('commit',{message:task.commit_message})}><GitCommit size={16}/>commit</button>{commitRetry?.taskId===task.id&&<button type="button" className="retry-commit" disabled={!passed||task.committed||busy} onClick={retryCommit}><GitCommit size={14}/>{busy?'در حال تلاش مجدد…':'تلاش مجدد با git add .'}</button>}<button type="button" className="push" disabled={!task.committed||task.pushed||busy} onClick={()=>action('push')}><Upload size={16}/>push</button><button type="button" className="merge-request" disabled={!task.pushed||!!task.merge_request_url||busy} onClick={()=>action('merge-request')}><GitPullRequest size={16}/>{task.merge_request_url?'MR ساخته شد':'Create MR'}</button><button type="button" className="delete-session delivery-delete" onClick={deleteSession} disabled={busy||running} title={running?'ابتدا اجرای سشن را متوقف کن':'حذف سشن'}><Trash2 size={15}/>حذف سشن</button></div></div>
            <details className="codex-cli" aria-label="Codex CLI">
              <summary className="codex-cli-title"><Terminal size={16}/> وضعیت Codex <small>معادل /status و /model</small></summary>
              <button type="button" className="codex-status-refresh" onClick={refreshCodexStatus} disabled={codexStatusLoading}>{codexStatusLoading?'در حال خواندن…':'به‌روزرسانی'}</button>
              <button type="button" className={`windows-notifications ${windowsNotifications?'active':''}`} onClick={toggleWindowsNotifications} aria-pressed={windowsNotifications}><Bell size={14}/>{windowsNotifications?'اعلان ویندوز فعال است':'فعال‌سازی اعلان ویندوز'}</button>
              {!codexStatus?<p className="codex-status-empty">{codexStatusLoading?'در حال اتصال به Codex…':'وضعیت Codex در دسترس نیست.'}</p>:<><div className="codex-status-overview"><div><small>حساب</small><b>{codexStatus.account?.planType||codexStatus.account?.type||'—'}</b></div><div><small>مدل پیش‌فرض</small><b dir="ltr">{activeCodexModel?.displayName||activeCodexModel?.model||'—'}</b></div><div><small>مصرف امروز</small><b>{number(codexUsage.at(-1)?.tokens)} token</b></div><div><small>مصرف ۷ روز اخیر</small><b>{number(codexUsage.slice(-7).reduce((sum,bucket)=>sum+(bucket.tokens||0),0))} token</b></div></div><div className="codex-rate-limits">{visibleCodexRateLimits.map(limit=><article key={limit.limitId}><b>{limit.limitName||limit.limitId||'Codex'}</b>{limit.primary&&<span>باقی‌مانده {number(100-(limit.primary.usedPercent||0))}٪ در بازهٔ {number(limit.primary.windowDurationMins)} دقیقه <small>ریست: {resetAt(limit.primary.resetsAt)}</small></span>}{limit.secondary&&<span>باقی‌مانده {number(100-(limit.secondary.usedPercent||0))}٪ در بازهٔ {number(limit.secondary.windowDurationMins)} دقیقه <small>ریست: {resetAt(limit.secondary.resetsAt)}</small></span>}</article>)}</div>{codexStatus.models?.length>0&&<small className="codex-models">مدل‌های قابل انتخاب: {codexStatus.models.map(model=>model.displayName||model.model).join('، ')}</small>}</>}
            </details>
          </>}
        </section>
      </div>
    </main>
    {showTodoModal&&<div className="todo-modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setShowTodoModal(false)}}><div className="todo-modal" role="dialog" aria-modal="true" aria-label="کارهای بعدی"><button className="todo-modal-close" type="button" onClick={()=>setShowTodoModal(false)} aria-label="بستن">×</button><TodoPanel task={task} sessions={sessions} todoDraft={todoDraft} setTodoDraft={setTodoDraft} todoTarget={todoTarget} setTodoTarget={setTodoTarget} addTodo={addTodo} sendTodo={sendTodo} removeTodo={removeTodo} busy={busy} running={running}/></div></div>}
  </div>
}
createRoot(document.getElementById('root')).render(<App/>);
